In [1]:
import LinnearProgramation.simplex_algorithm as simplex
import LinnearProgramation.simplex_algorithm_tabulate as tabulate
import numpy as np
import copy

In [2]:
# Numpy Configurations
np.set_printoptions(precision=4, edgeitems=10)
np.core.arrayprint._line_width = 180

### Simplex

In [3]:
A = np.matrix([[1, 0, 1, 2], [0, 1, 0, 1]])
b = np.array([4, 1])
c = np.array([0, 0, 1, 1])
variables = ["x3", "x4", "x1", "x2"]

In [4]:
simplex.simplex(copy.deepcopy(A), copy.deepcopy(b), copy.deepcopy(c), copy.deepcopy(variables))



Iteration  1 
[ x_B ,  x_N ] = [ x3, x4, x1, x2 ]

Matrix A
[[1 0 1 2]
 [0 1 0 1]]

Vector b
[4 1]

Vector c
[0 0 1 1]

Basis
[[1 0]
 [0 1]]

Basis Inverse
[[1. 0.]
 [0. 1.]]

BFS
[4. 1. 0. 0.]


Optimality reached

The optimal BFS is
[ x3, x4, x1, x2 ] = [ 4.0, 1.0, 0.0, 0.0 ]

With performance z = 0.0


### Simplex Tabulate

In [5]:
A = np.matrix([[1, 2, 1, 0], [0, 1, 0, 1]])
b = np.array([4, 1])
c = np.array([1, 1, 0, 0])
variables = ['x' + str(i) for i in range(1, len(c) + 1)]
m, n = np.shape(A)
basic_indexes = range(m, n)
non_basic_indexes = range(m)

In [6]:
tableau, basic_variables, non_basic_variables = tabulate.generate_table(A, b, c, variables, basic_indexes, non_basic_indexes, m, n)

In [7]:
tabulate.simplex_tableau(copy.deepcopy(tableau), copy.deepcopy(basic_variables), copy.deepcopy(non_basic_variables))



Iteration  1 
[ x_B ,  x_N ] = [ x3, x4, x1, x2 ]


Entry tableau
[[ 1.  0.  0. -1. -1.  0.]
 [ 0.  1.  0.  1.  2.  4.]
 [ 0.  0.  1.  0.  1.  1.]]


Optimality reached

The optimal BFS is
[ x3, x4, x1, x2 ] = [ 4.0, 1.0, 0.0, 0.0 ]

With performance z = 0.0
