In [1]:
import LinnearProgramation.simplex_algorithm as simplex
import LinnearProgramation.simplex_algorithm_tabulate as tabulate
import numpy as np
import copy

In [2]:
# Numpy Configurations
np.set_printoptions(precision=4, edgeitems=10)
np.core.arrayprint._line_width = 180

### Simplex

In [3]:
A = np.matrix([[1, 0, 0, 1, 1, 2], [0, 1, 0, 1, 1, -1], [0, 0, 1, -1, 1, 1]])
b = np.array([9, 2, 4])
c = np.array([0, 0, 0, 1, 1, -4])
variables = ["x3", "x4", "x5", "x1", "x2", "x3"]

In [4]:
simplex.simplex(copy.deepcopy(A), copy.deepcopy(b), copy.deepcopy(c), copy.deepcopy(variables))



Iteration  1 
[ x_B ,  x_N ] = [ x3, x4, x5, x1, x2, x3 ]

Matrix A
[[ 1  0  0  1  1  2]
 [ 0  1  0  1  1 -1]
 [ 0  0  1 -1  1  1]]

Vector b
[9 2 4]

Vector c
[ 0  0  0  1  1 -4]

Basis
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Basis Inverse
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

BFS
[9. 2. 4. 0. 0. 0.]

k = 6 -> column no. 6 of Matrix A ( x3 )
y_k
[ 2. -1.  1.]

r = 3 -> column no. 3 of Basis  ( x5 )
x_k
4.0

 x3 enters and  x5 leaves the basis


Iteration  2 
[ x_B ,  x_N ] = [ x3, x4, x3, x1, x2, x5 ]

Matrix A
[[ 1  0  2  1  1  0]
 [ 0  1 -1  1  1  0]
 [ 0  0  1 -1  1  1]]

Vector b
[9 2 4]

Vector c
[ 0  0 -4  1  1  0]

Basis
[[ 1  0  2]
 [ 0  1 -1]
 [ 0  0  1]]

Basis Inverse
[[ 1.  0. -2.]
 [ 0.  1.  1.]
 [ 0.  0.  1.]]

BFS
[1. 6. 4. 0. 0. 0.]

k = 4 -> column no. 4 of Matrix A ( x1 )
y_k
[ 3.  0. -1.]

r = 1 -> column no. 1 of Basis  ( x3 )
x_k
0.3333333333333333

 x1 enters and  x3 leaves the basis


Iteration  3 
[ x_B ,  x_N ] = [ x1, x4, x3, x3, x2, x5 ]

Matrix A
[[ 1  0  2  1  1  0

### Simplex Tabulate

In [5]:
A = np.matrix([[1, 1, 2, 1, 0, 0], [1, 1, -1, 0, 1, 0], [-1, 1, 1, 0, 0, 1]])
b = np.array([9, 2, 4])
c = np.array([1, 1, -4, 0, 0, 0])
variables = ['x' + str(i) for i in range(1, len(c) + 1)]
m, n = np.shape(A)
basic_indexes = range(m, n)
non_basic_indexes = range(m)

In [6]:
tableau, basic_variables, non_basic_variables = tabulate.generate_table(A, b, c, variables, basic_indexes, non_basic_indexes, m, n)

In [7]:
tabulate.simplex_tableau(copy.deepcopy(tableau), copy.deepcopy(basic_variables), copy.deepcopy(non_basic_variables))



Iteration  1 
[ x_B ,  x_N ] = [ x4, x5, x6, x1, x2, x3 ]


Entry tableau
[[ 1.  0.  0.  0. -1. -1.  4.  0.]
 [ 0.  1.  0.  0.  1.  1.  2.  9.]
 [ 0.  0.  1.  0.  1.  1. -1.  2.]
 [ 0.  0.  0.  1. -1.  1.  1.  4.]]

k = 3 -> column no. 3 of x_N part ( x3 )
y_k
[ 2. -1.  1.]

r = 3 -> column no. 3 of x_B part ( x6 )
x_Br
4.0

pivot = 1.0

Pivoted tableau
[[  1.   0.   0.  -4.   3.  -5.   0. -16.]
 [  0.   1.   0.  -2.   3.  -1.   0.   1.]
 [  0.   0.   1.   1.   0.   2.   0.   6.]
 [  0.   0.   0.   1.  -1.   1.   1.   4.]]

 x3 enters and  x6 leaves the basis


Iteration  2 
[ x_B ,  x_N ] = [ x4, x5, x3, x1, x2, x6 ]


Entry tableau
[[  1.   0.   0.  -4.   3.  -5.   0. -16.]
 [  0.   1.   0.  -2.   3.  -1.   0.   1.]
 [  0.   0.   1.   1.   0.   2.   0.   6.]
 [  0.   0.   0.   1.  -1.   1.   1.   4.]]

k = 1 -> column no. 1 of x_N part ( x1 )
y_k
[ 3.  0. -1.]

r = 1 -> column no. 1 of x_B part ( x4 )
x_Br
0.3333333333333333

pivot = 3.0

Pivoted tableau
[[  1.      -1.       0.   