# Algoritmo Simplex por Tabulado
**Suárez Pérez Juan Pablo**

Minimizar:  
$x_{1}+x_{2}-4x_{3}.$  
  
Sujeto a:  
$x_1+x_2+2x_3\leq9.$  
$x_1+x_2-x_3\leq2.$  
$-x_1+x_2+x_3\leq4.$  
$x_1,x_2,x_3,\geq0.$

Introducimos las variables de holgura:  
$x_1+x_2-4x_3+0x_4+0x_5+0x_6.$  
$x_1+x_2+2x_3+x_4+0x_5+0x_6=9.$  
$x_1+x_2-x_3+0x_4+x_5+0x_6=2.$  
$-x_1+x_2+x_3+0x_4+0x_5+x_6=4.$  
$x_1,x_2,x_3,x_4,x_5,x_6\geq0$ 

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 1, 2, 1, 0, 0], 
              [1, 1, -1, 0, 1, 0],
              [-1, 1, 1, 0, 0, 1],])

In [3]:
B = np.array([[1, 0, 0],
             [0, 1, 0],
             [0, 0, 1]])

In [4]:
N = np.array([[1, 1, 2],
              [1, 1, -1],
              [-1, 1, 1]])

In [5]:
C = np.array([1, 1, -4, 0, 0, 0])
CN = np.array([1, 1, -4])
CB = np.array([0, 0, 0])

In [6]:
b = np.array([9, 2, 4])

In [7]:
b_ = np.linalg.inv(B) @ b

In [8]:
one_array = np.ones(1, dtype=int)
identity_matrix = np.eye(3)
zero_array = np.zeros(3, dtype=int)

In [19]:
ZXN = CB @ np.linalg.inv(B) @ N - CN
XBXN = np.linalg.inv(B) @ N
ZRHS = np.full((1), CB @ b_)
XBRHS = b_ 

In [21]:
ZXN

array([-1., -1.,  4.])

In [22]:
TABLE = np.concatenate((one_array, zero_array, ZXN, ZRHS), axis=0)

In [30]:
XBRHS

array([9., 2., 4.])

In [31]:
fila2 = np.concatenate((zero_array.T, identity_matrix, XBXN, XBRHS.T), axis=3)

AxisError: axis 3 is out of bounds for array of dimension 1

In [37]:
fila2 = np.concatenate((zero_array, identity_matrix), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [39]:
zero_array

array([0, 0, 0])

In [23]:
print(TABLE)

[ 1.  0.  0.  0. -1. -1.  4.  0.]


In [33]:
min(TABLE[0][2])

-1.0